dataset: speech-waveform
model_name: ASTEmbeddingTransformer
model_class: FineTunedAST
lr: 0.00005
batch_size: 64
scheduler_factor: 0.2
scheduler_patience: 8
epochs: 40

config_dir: ast-feature-extractor-config
max_length: 100

feature_processor: ASTAugmenterProcessor
feature_processor_params:
  - config_dir
  - max_length
  - time_stretch
  - freq_mask
  - time_mask
time_stretch: 0.3
freq_mask: 30
time_mask: 30

model_params:
  - config_dir
  - max_length
  - attention_probs_dropout_prob
  - hidden_dropout_prob
attention_probs_dropout_prob: 0.2
hidden_dropout_prob: 0.2
