dataset: speech-waveform
model_name: ASTEmbeddingTransformer
model_class: FineTunedAST
lr: 0.000005
beta1: 0.93
beta2: 0.9
batch_size: 32
epochs: 20

config_dir: ast-feature-extractor-config
max_length: 100

feature_processor: ASTProcessor
feature_processor_params:
  - config_dir
  - max_length
augmentations:
  spectrogram: true
  time_stretch: 1.1  # Stretch by 10%
  freq_mask: 30     # Maximum frequency mask width
  time_mask: 100    # Maximum time mask width

model_params:
  - config_dir
  - max_length
