dataset: speech-waveform
model_name: ASTEmbeddingTransformer
model_class: FineTunedAST
lr: 0.00001
batch_size: 3
epochs: 5

config_dir: ast-feature-extractor-config
max_length: 100

feature_processor: ASTProcessor
feature_processor_params:
  - config_dir
  - max_length

model_params:
  - config_dir
  - max_length
