dataset: speech-waveform
model_name: TransformerASTEmbedding
model_class: TransformerASTModel
feature_processor: ASTProcessor

lr: 0.00003
batch_size: 128
epochs: 20

hidden_vector_size: 512
heads_num: 4
hidden_layer_size: 2048
layers_num: 4
dropout: 0.1
model_params:
  - hidden_vector_size
  - heads_num
  - hidden_layer_size
  - layers_num
  - dropout
