dataset: speech-waveform
model_name: TransformerASTEmbedding
model_class: TransformerASTModel
lr: 0.00003
beta1: 0.97
beta2: 0.9
batch_size: 128
epochs: 20

config_dir: ast-feature-extractor-config
max_length: 100

feature_processor: ASTProcessor
feature_processor_params:
  - config_dir
  - max_length

model_params:
  - config_dir
  - max_length
  - hidden_vector_size
  - heads_num
  - hidden_layer_size
  - layers_num
  - dropout
hidden_vector_size: 512
heads_num: 4
hidden_layer_size: 2048
layers_num: 4
dropout: 0.2
