dataset: speech-waveform
model_name: TransformerASTEmbedding
model_class: TransformerASTModel
feature_processor: ASTProcessor

lr: 0.0001
batch_size: 64
epochs: 30

hidden_vector_size: 256
heads_num: 4
hidden_layer_size: 1024
layers_num: 2
dropout: 0.2
model_params:
  - hidden_vector_size
  - heads_num
  - hidden_layer_size
  - layers_num
  - dropout
