dataset: speech-waveform
model_name: TransformerASTEmbedding
model_class: TransformerASTModel
lr: 0.000319
beta1: 0.874
beta2: 0.977
scheduler_factor: 0.3
scheduler_patience: 6
batch_size: 256
epochs: 50

config_dir: ast-feature-extractor-config
max_length: 100

feature_processor: ASTNormalizedProcessor
feature_processor_params:
  - config_dir
  - max_length

model_params:
  - config_dir
  - max_length
  - hidden_vector_size
  - heads_num
  - hidden_layer_size
  - layers_num
  - dropout
hidden_vector_size: 512
heads_num: 4
hidden_layer_size: 2048
layers_num: 4
dropout: 0.32
