dataset: speech-waveform
model_name: lstm
model_class: LSTMModel

lr: 0.000001 # Learning rate
batch_size: 32
epochs: 1

input_size: 3200
embedding_hidden: 512 # Hidden units in embedding layer
hidden_vector_size: 128 # LSTM hidden state size
layers_num: 2 # Number of LSTM layers
dropout: 0.5 # Dropout rate in LSTM for regularization
model_params:
  - input_size
  - embedding_hidden
  - hidden_vector_size
  - layers_num
  - dropout
