dataset: speech-waveform
model_name: lstm
model_class: LSTMModel

lr: 0.001 # Learning rate
batch_size: 256
epochs: 20

config_dir: ast-feature-extractor-config
max_length: 100
num_mel_bins: 128

feature_processor: ASTProcessor
feature_processor_params:
  - config_dir
  - max_length
  - num_mel_bins

hidden_layer_size: 512 # LSTM hidden state size
layers_num: 2 # Number of LSTM layers
dropout: 0.2 # Dropout rate in LSTM for regularization
model_params:
  - num_mel_bins
  - hidden_layer_size
  - layers_num
  - dropout
