dataset: speech-waveform
model_name: rnn
model_class: RNNModel

lr: 0.001 # Learning rate
scheduler_factor: 0.2
scheduler_patience: 8
batch_size: 256
epochs: 40

config_dir: ast-feature-extractor-config
max_length: 100
num_mel_bins: 128

feature_processor: ASTProcessor
feature_processor_params:
  - config_dir
  - max_length
  - num_mel_bins

hidden_layer_size: 512
layers_num: 2
bidirectional: true
dropout: 0.2
model_params:
  - num_mel_bins
  - hidden_layer_size
  - layers_num
  - bidirectional
  - dropout
